agent:
  name: my_test_agent
  description: "Diffusers image to image generation"

templates:
  - template_name: InputTemplate
    class_name: InputTemplate
    attributes: {}

  - template_name: LongestMaxSize
    class_name: LongestMaxSizeWrapper
    template_input: InputTemplate
    attributes:
      longestmaxsize_init:
        max_size: 1024

  - template_name: PadIfNeeded
    class_name: PadIfNeededWrapper
    template_input: LongestMaxSize
    attributes:
      padifneeded_init:
        min_height: 1024
        min_width: 1024
        border_mode: 0
        fill_mask: 0

  - template_name: ImageToImageDiffusers
    class_name: ImageToImageDiffusers
    template_input: PadIfNeeded
    attributes:
      model_path: stable-diffusion-v1-5/stable-diffusion-v1-5
      device: cuda
      torch_dtype: "float16"
      seed: 42
      enable_model_cpu_offload: false
      overwrite_images: true
      generation_params:
        prompt: "A majestic castle on top of a mountain, surrounded by clouds during sunset"
        height: 1024
        width: 1024
        num_inference_steps: 50
        guidance_scale: 7.5
        negative_prompt: "low quality, blurry, distorted"
        strength: 0.75
        num_images_per_prompt: 1