agent:
  name: my_test_agent
  description: "Diffusers image inpainting"

templates:
  - template_name: InputTemplate
    class_name: InputTemplate
    attributes: {}

  - template_name: LongestMaxSize
    class_name: LongestMaxSizeWrapper
    template_input: InputTemplate
    attributes:
      longestmaxsize_init:
        max_size: 1024

  - template_name: PadIfNeeded
    class_name: PadIfNeededWrapper
    template_input: LongestMaxSize
    attributes:
      padifneeded_init:
        min_height: 1024
        min_width: 1024
        border_mode: 0
        fill_mask: 0

  - template_name: GroundingDINO
    class_name: GroundingDINO
    template_input: PadIfNeeded
    attributes:
      model_path: IDEA-Research/grounding-dino-base
      inference_mode: zero_shot
      text_input: a mountain.
      device: cuda
      threshold: 0.4
      text_threshold: 0.3

  - template_name: UltralyticsSAM
    class_name: UltralyticsPredict
    template_input: GroundingDINO
    attributes:
      model_class: SAM
      model: sam2_t.pt
      use_detections_as_sam_prompt: true

  - template_name: InpaintingDiffusers
    class_name: InpaintingDiffusers
    template_input: UltralyticsSAM
    attributes:
      model_path: stable-diffusion-v1-5/stable-diffusion-v1-5
      device: cuda
      torch_dtype: "float16"
      seed: 42
      enable_model_cpu_offload: false
      inpainting_mode: mask
      dilation_radius: 0
      preserve_outside_content: False
      overwrite_images: true
      generation_params:
        prompt: "concept art digital painting of an elven castle, inspired by lord of the rings, highly detailed, 8k"
        height: 1024
        width: 1024
        num_inference_steps: 50
        guidance_scale: 7.5
        negative_prompt: "low quality, blurry, distorted"
        strength: 0.75
        num_images_per_prompt: 1