agent:
  name: my_agent_test
  description: "GroundingDino image detection"

templates:
  - template_name: InputTemplate
    class_name: InputTemplate
    attributes: { }

  - template_name: GroundingDINO
    class_name: GroundingDINO
    template_input: InputTemplate
    attributes:
      model_path: IDEA-Research/grounding-dino-base
      inference_mode: zero_shot
      text_input: a person.
      device: cuda
      threshold: 0.2
      text_threshold: 0.3

  - template_name: BBoxDrawer
    class_name: BBoxDrawer
    template_input: GroundingDINO
    attributes:
      overwrite: true
      randomized_color: false