services:
  sinapsis-huggingface-main: &default
    image: sinapsis-huggingface:base
    build:
      context: ../
      dockerfile: docker/Dockerfile
      ssh:
        - default
    shm_size: '8gb'
    environment:
      PYTHONUNBUFFERED: 1
      GRADIO_SHARE_APP: ${GRADIO_SHARE_APP:-false}
      PYTHONPATH: /lib/python3.10/:/app/.venv/lib/python3.10/site-packages
    volumes:
      - "~/.cache/torch:/root/.cache/torch"
      - "~/.cache/sinapsis/:/root/.cache/sinapsis"
      - "~/.cache/huggingface/hub:/root/.cache/huggingface/hub"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
